events {}

http {
    server {
        listen 80;

        location /jwks {
            default_type application/json;
            return 200 '{"keys": []}';
        }

        location / {
            root /usr/share/nginx/html;
            index jwks.json;
        }

        location = /jwks.json {
            root /usr/share/nginx/html;
            default_type application/json;
        }
    }
}
